/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BroadcastingRouteImport } from './routes/broadcasting'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as HumanSupportRouteImport } from './routes/human-support'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSignupRouteImport } from './routes/api/signup'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CSkuRouteImport } from './routes/c.$sku'
import { Route as DDocumentIdRouteImport } from './routes/d.$documentId'
import { Route as FFileSlugRouteImport } from './routes/f.$fileSlug'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as ApiCronAutomationsRouteImport } from './routes/api/cron/automations'
import { Route as ApiWebhooksEmailRouteImport } from './routes/api/webhooks/email'
import { Route as ApiWebhooksFacebookRouteImport } from './routes/api/webhooks/facebook'
import { Route as ApiWebhooksIndiamartRouteImport } from './routes/api/webhooks/indiamart'
import { Route as ApiWebhooksInstagramRouteImport } from './routes/api/webhooks/instagram'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as ApiOauthGmailCallbackRouteImport } from './routes/api/oauth/gmail/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastingRoute = BroadcastingRouteImport.update({
  id: '/broadcasting',
  path: '/broadcasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanSupportRoute = HumanSupportRouteImport.update({
  id: '/human-support',
  path: '/human-support',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignupRoute = ApiSignupRouteImport.update({
  id: '/api/signup',
  path: '/api/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CSkuRoute = CSkuRouteImport.update({
  id: '/c/$sku',
  path: '/c/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const DDocumentIdRoute = DDocumentIdRouteImport.update({
  id: '/d/$documentId',
  path: '/d/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FFileSlugRoute = FFileSlugRouteImport.update({
  id: '/f/$fileSlug',
  path: '/f/$fileSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutomationsRoute = ApiCronAutomationsRouteImport.update({
  id: '/api/cron/automations',
  path: '/api/cron/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksEmailRoute = ApiWebhooksEmailRouteImport.update({
  id: '/api/webhooks/email',
  path: '/api/webhooks/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksFacebookRoute = ApiWebhooksFacebookRouteImport.update({
  id: '/api/webhooks/facebook',
  path: '/api/webhooks/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksIndiamartRoute = ApiWebhooksIndiamartRouteImport.update({
  id: '/api/webhooks/indiamart',
  path: '/api/webhooks/indiamart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksInstagramRoute = ApiWebhooksInstagramRouteImport.update({
  id: '/api/webhooks/instagram',
  path: '/api/webhooks/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGmailCallbackRoute = ApiOauthGmailCallbackRouteImport.update({
  id: '/api/oauth/gmail/callback',
  path: '/api/oauth/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/agents': typeof AgentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/broadcasting': typeof BroadcastingRoute
  '/channels': typeof ChannelsRoute
  '/command-center': typeof CommandCenterRoute
  '/customers': typeof CustomersRoute
  '/dpa': typeof DpaRoute
  '/embed': typeof EmbedRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formulas': typeof FormulasRoute
  '/human-support': typeof HumanSupportRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/signup': typeof ApiSignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$sku': typeof CSkuRoute
  '/d/$documentId': typeof DDocumentIdRoute
  '/f/$fileSlug': typeof FFileSlugRoute
  '/platform/': typeof PlatformIndexRoute
  '/api/cron/automations': typeof ApiCronAutomationsRoute
  '/api/webhooks/email': typeof ApiWebhooksEmailRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/indiamart': typeof ApiWebhooksIndiamartRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/agents': typeof AgentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/broadcasting': typeof BroadcastingRoute
  '/channels': typeof ChannelsRoute
  '/command-center': typeof CommandCenterRoute
  '/customers': typeof CustomersRoute
  '/dpa': typeof DpaRoute
  '/embed': typeof EmbedRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formulas': typeof FormulasRoute
  '/human-support': typeof HumanSupportRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/signup': typeof ApiSignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$sku': typeof CSkuRoute
  '/d/$documentId': typeof DDocumentIdRoute
  '/f/$fileSlug': typeof FFileSlugRoute
  '/platform': typeof PlatformIndexRoute
  '/api/cron/automations': typeof ApiCronAutomationsRoute
  '/api/webhooks/email': typeof ApiWebhooksEmailRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/indiamart': typeof ApiWebhooksIndiamartRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/agents': typeof AgentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/broadcasting': typeof BroadcastingRoute
  '/channels': typeof ChannelsRoute
  '/command-center': typeof CommandCenterRoute
  '/customers': typeof CustomersRoute
  '/dpa': typeof DpaRoute
  '/embed': typeof EmbedRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formulas': typeof FormulasRoute
  '/human-support': typeof HumanSupportRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/signup': typeof ApiSignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$sku': typeof CSkuRoute
  '/d/$documentId': typeof DDocumentIdRoute
  '/f/$fileSlug': typeof FFileSlugRoute
  '/platform/': typeof PlatformIndexRoute
  '/api/cron/automations': typeof ApiCronAutomationsRoute
  '/api/webhooks/email': typeof ApiWebhooksEmailRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/indiamart': typeof ApiWebhooksIndiamartRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/agents'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/broadcasting'
    | '/channels'
    | '/command-center'
    | '/customers'
    | '/dpa'
    | '/embed'
    | '/features'
    | '/forgot-password'
    | '/formulas'
    | '/human-support'
    | '/inbox'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/status'
    | '/support'
    | '/terms'
    | '/tools'
    | '/api/health'
    | '/api/signup'
    | '/auth/callback'
    | '/c/$sku'
    | '/d/$documentId'
    | '/f/$fileSlug'
    | '/platform/'
    | '/api/cron/automations'
    | '/api/webhooks/email'
    | '/api/webhooks/facebook'
    | '/api/webhooks/indiamart'
    | '/api/webhooks/instagram'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/stripe'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/gmail/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/agents'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/broadcasting'
    | '/channels'
    | '/command-center'
    | '/customers'
    | '/dpa'
    | '/embed'
    | '/features'
    | '/forgot-password'
    | '/formulas'
    | '/human-support'
    | '/inbox'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/status'
    | '/support'
    | '/terms'
    | '/tools'
    | '/api/health'
    | '/api/signup'
    | '/auth/callback'
    | '/c/$sku'
    | '/d/$documentId'
    | '/f/$fileSlug'
    | '/platform'
    | '/api/cron/automations'
    | '/api/webhooks/email'
    | '/api/webhooks/facebook'
    | '/api/webhooks/indiamart'
    | '/api/webhooks/instagram'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/stripe'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/gmail/callback'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/agents'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/broadcasting'
    | '/channels'
    | '/command-center'
    | '/customers'
    | '/dpa'
    | '/embed'
    | '/features'
    | '/forgot-password'
    | '/formulas'
    | '/human-support'
    | '/inbox'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/status'
    | '/support'
    | '/terms'
    | '/tools'
    | '/api/health'
    | '/api/signup'
    | '/auth/callback'
    | '/c/$sku'
    | '/d/$documentId'
    | '/f/$fileSlug'
    | '/platform/'
    | '/api/cron/automations'
    | '/api/webhooks/email'
    | '/api/webhooks/facebook'
    | '/api/webhooks/indiamart'
    | '/api/webhooks/instagram'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/stripe'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/gmail/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AgentsRoute: typeof AgentsRoute
  AiChatRoute: typeof AiChatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomationRoute: typeof AutomationRoute
  BroadcastingRoute: typeof BroadcastingRoute
  ChannelsRoute: typeof ChannelsRoute
  CommandCenterRoute: typeof CommandCenterRoute
  CustomersRoute: typeof CustomersRoute
  DpaRoute: typeof DpaRoute
  EmbedRoute: typeof EmbedRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FormulasRoute: typeof FormulasRoute
  HumanSupportRoute: typeof HumanSupportRoute
  InboxRoute: typeof InboxRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSignupRoute: typeof ApiSignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CSkuRoute: typeof CSkuRoute
  DDocumentIdRoute: typeof DDocumentIdRoute
  FFileSlugRoute: typeof FFileSlugRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  ApiCronAutomationsRoute: typeof ApiCronAutomationsRoute
  ApiWebhooksEmailRoute: typeof ApiWebhooksEmailRoute
  ApiWebhooksFacebookRoute: typeof ApiWebhooksFacebookRoute
  ApiWebhooksIndiamartRoute: typeof ApiWebhooksIndiamartRoute
  ApiWebhooksInstagramRoute: typeof ApiWebhooksInstagramRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
  ApiOauthGmailCallbackRoute: typeof ApiOauthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasting': {
      id: '/broadcasting'
      path: '/broadcasting'
      fullPath: '/broadcasting'
      preLoaderRoute: typeof BroadcastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-support': {
      id: '/human-support'
      path: '/human-support'
      fullPath: '/human-support'
      preLoaderRoute: typeof HumanSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signup': {
      id: '/api/signup'
      path: '/api/signup'
      fullPath: '/api/signup'
      preLoaderRoute: typeof ApiSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sku': {
      id: '/c/$sku'
      path: '/c/$sku'
      fullPath: '/c/$sku'
      preLoaderRoute: typeof CSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$documentId': {
      id: '/d/$documentId'
      path: '/d/$documentId'
      fullPath: '/d/$documentId'
      preLoaderRoute: typeof DDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$fileSlug': {
      id: '/f/$fileSlug'
      path: '/f/$fileSlug'
      fullPath: '/f/$fileSlug'
      preLoaderRoute: typeof FFileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/automations': {
      id: '/api/cron/automations'
      path: '/api/cron/automations'
      fullPath: '/api/cron/automations'
      preLoaderRoute: typeof ApiCronAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/email': {
      id: '/api/webhooks/email'
      path: '/api/webhooks/email'
      fullPath: '/api/webhooks/email'
      preLoaderRoute: typeof ApiWebhooksEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/facebook': {
      id: '/api/webhooks/facebook'
      path: '/api/webhooks/facebook'
      fullPath: '/api/webhooks/facebook'
      preLoaderRoute: typeof ApiWebhooksFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/indiamart': {
      id: '/api/webhooks/indiamart'
      path: '/api/webhooks/indiamart'
      fullPath: '/api/webhooks/indiamart'
      preLoaderRoute: typeof ApiWebhooksIndiamartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/instagram': {
      id: '/api/webhooks/instagram'
      path: '/api/webhooks/instagram'
      fullPath: '/api/webhooks/instagram'
      preLoaderRoute: typeof ApiWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/gmail/callback': {
      id: '/api/oauth/gmail/callback'
      path: '/api/oauth/gmail/callback'
      fullPath: '/api/oauth/gmail/callback'
      preLoaderRoute: typeof ApiOauthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AgentsRoute: AgentsRoute,
  AiChatRoute: AiChatRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomationRoute: AutomationRoute,
  BroadcastingRoute: BroadcastingRoute,
  ChannelsRoute: ChannelsRoute,
  CommandCenterRoute: CommandCenterRoute,
  CustomersRoute: CustomersRoute,
  DpaRoute: DpaRoute,
  EmbedRoute: EmbedRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FormulasRoute: FormulasRoute,
  HumanSupportRoute: HumanSupportRoute,
  InboxRoute: InboxRoute,
  KnowledgeRoute: KnowledgeRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSignupRoute: ApiSignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CSkuRoute: CSkuRoute,
  DDocumentIdRoute: DDocumentIdRoute,
  FFileSlugRoute: FFileSlugRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  ApiCronAutomationsRoute: ApiCronAutomationsRoute,
  ApiWebhooksEmailRoute: ApiWebhooksEmailRoute,
  ApiWebhooksFacebookRoute: ApiWebhooksFacebookRoute,
  ApiWebhooksIndiamartRoute: ApiWebhooksIndiamartRoute,
  ApiWebhooksInstagramRoute: ApiWebhooksInstagramRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
  ApiOauthGmailCallbackRoute: ApiOauthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
