/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BroadcastingRouteImport } from './routes/broadcasting'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as HumanSupportRouteImport } from './routes/human-support'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as CSkuRouteImport } from './routes/c.$sku'
import { Route as DDocumentIdRouteImport } from './routes/d.$documentId'
import { Route as ApiCronAutomationsRouteImport } from './routes/api/cron/automations'
import { Route as ApiWebhooksEmailRouteImport } from './routes/api/webhooks/email'
import { Route as ApiWebhooksFacebookRouteImport } from './routes/api/webhooks/facebook'
import { Route as ApiWebhooksIndiamartRouteImport } from './routes/api/webhooks/indiamart'
import { Route as ApiWebhooksInstagramRouteImport } from './routes/api/webhooks/instagram'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as ApiOauthGmailCallbackRouteImport } from './routes/api/oauth/gmail/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastingRoute = BroadcastingRouteImport.update({
  id: '/broadcasting',
  path: '/broadcasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanSupportRoute = HumanSupportRouteImport.update({
  id: '/human-support',
  path: '/human-support',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CSkuRoute = CSkuRouteImport.update({
  id: '/c/$sku',
  path: '/c/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const DDocumentIdRoute = DDocumentIdRouteImport.update({
  id: '/d/$documentId',
  path: '/d/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutomationsRoute = ApiCronAutomationsRouteImport.update({
  id: '/api/cron/automations',
  path: '/api/cron/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksEmailRoute = ApiWebhooksEmailRouteImport.update({
  id: '/api/webhooks/email',
  path: '/api/webhooks/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksFacebookRoute = ApiWebhooksFacebookRouteImport.update({
  id: '/api/webhooks/facebook',
  path: '/api/webhooks/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksIndiamartRoute = ApiWebhooksIndiamartRouteImport.update({
  id: '/api/webhooks/indiamart',
  path: '/api/webhooks/indiamart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksInstagramRoute = ApiWebhooksInstagramRouteImport.update({
  id: '/api/webhooks/instagram',
  path: '/api/webhooks/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGmailCallbackRoute = ApiOauthGmailCallbackRouteImport.update({
  id: '/api/oauth/gmail/callback',
  path: '/api/oauth/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/broadcasting': typeof BroadcastingRoute
  '/channels': typeof ChannelsRoute
  '/command-center': typeof CommandCenterRoute
  '/customers': typeof CustomersRoute
  '/embed': typeof EmbedRoute
  '/human-support': typeof HumanSupportRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/c/$sku': typeof CSkuRoute
  '/d/$documentId': typeof DDocumentIdRoute
  '/api/cron/automations': typeof ApiCronAutomationsRoute
  '/api/webhooks/email': typeof ApiWebhooksEmailRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/indiamart': typeof ApiWebhooksIndiamartRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/broadcasting': typeof BroadcastingRoute
  '/channels': typeof ChannelsRoute
  '/command-center': typeof CommandCenterRoute
  '/customers': typeof CustomersRoute
  '/embed': typeof EmbedRoute
  '/human-support': typeof HumanSupportRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/c/$sku': typeof CSkuRoute
  '/d/$documentId': typeof DDocumentIdRoute
  '/api/cron/automations': typeof ApiCronAutomationsRoute
  '/api/webhooks/email': typeof ApiWebhooksEmailRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/indiamart': typeof ApiWebhooksIndiamartRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/broadcasting': typeof BroadcastingRoute
  '/channels': typeof ChannelsRoute
  '/command-center': typeof CommandCenterRoute
  '/customers': typeof CustomersRoute
  '/embed': typeof EmbedRoute
  '/human-support': typeof HumanSupportRoute
  '/inbox': typeof InboxRoute
  '/knowledge': typeof KnowledgeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/c/$sku': typeof CSkuRoute
  '/d/$documentId': typeof DDocumentIdRoute
  '/api/cron/automations': typeof ApiCronAutomationsRoute
  '/api/webhooks/email': typeof ApiWebhooksEmailRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
  '/api/webhooks/indiamart': typeof ApiWebhooksIndiamartRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/oauth/gmail/callback': typeof ApiOauthGmailCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/broadcasting'
    | '/channels'
    | '/command-center'
    | '/customers'
    | '/embed'
    | '/human-support'
    | '/inbox'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/reports'
    | '/settings'
    | '/tools'
    | '/c/$sku'
    | '/d/$documentId'
    | '/api/cron/automations'
    | '/api/webhooks/email'
    | '/api/webhooks/facebook'
    | '/api/webhooks/indiamart'
    | '/api/webhooks/instagram'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/gmail/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/broadcasting'
    | '/channels'
    | '/command-center'
    | '/customers'
    | '/embed'
    | '/human-support'
    | '/inbox'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/reports'
    | '/settings'
    | '/tools'
    | '/c/$sku'
    | '/d/$documentId'
    | '/api/cron/automations'
    | '/api/webhooks/email'
    | '/api/webhooks/facebook'
    | '/api/webhooks/indiamart'
    | '/api/webhooks/instagram'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/gmail/callback'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/ai-chat'
    | '/analytics'
    | '/automation'
    | '/broadcasting'
    | '/channels'
    | '/command-center'
    | '/customers'
    | '/embed'
    | '/human-support'
    | '/inbox'
    | '/knowledge'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/products'
    | '/reports'
    | '/settings'
    | '/tools'
    | '/c/$sku'
    | '/d/$documentId'
    | '/api/cron/automations'
    | '/api/webhooks/email'
    | '/api/webhooks/facebook'
    | '/api/webhooks/indiamart'
    | '/api/webhooks/instagram'
    | '/api/webhooks/whatsapp'
    | '/api/oauth/gmail/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AiChatRoute: typeof AiChatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomationRoute: typeof AutomationRoute
  BroadcastingRoute: typeof BroadcastingRoute
  ChannelsRoute: typeof ChannelsRoute
  CommandCenterRoute: typeof CommandCenterRoute
  CustomersRoute: typeof CustomersRoute
  EmbedRoute: typeof EmbedRoute
  HumanSupportRoute: typeof HumanSupportRoute
  InboxRoute: typeof InboxRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  CSkuRoute: typeof CSkuRoute
  DDocumentIdRoute: typeof DDocumentIdRoute
  ApiCronAutomationsRoute: typeof ApiCronAutomationsRoute
  ApiWebhooksEmailRoute: typeof ApiWebhooksEmailRoute
  ApiWebhooksFacebookRoute: typeof ApiWebhooksFacebookRoute
  ApiWebhooksIndiamartRoute: typeof ApiWebhooksIndiamartRoute
  ApiWebhooksInstagramRoute: typeof ApiWebhooksInstagramRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
  ApiOauthGmailCallbackRoute: typeof ApiOauthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasting': {
      id: '/broadcasting'
      path: '/broadcasting'
      fullPath: '/broadcasting'
      preLoaderRoute: typeof BroadcastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-support': {
      id: '/human-support'
      path: '/human-support'
      fullPath: '/human-support'
      preLoaderRoute: typeof HumanSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sku': {
      id: '/c/$sku'
      path: '/c/$sku'
      fullPath: '/c/$sku'
      preLoaderRoute: typeof CSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$documentId': {
      id: '/d/$documentId'
      path: '/d/$documentId'
      fullPath: '/d/$documentId'
      preLoaderRoute: typeof DDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/automations': {
      id: '/api/cron/automations'
      path: '/api/cron/automations'
      fullPath: '/api/cron/automations'
      preLoaderRoute: typeof ApiCronAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/email': {
      id: '/api/webhooks/email'
      path: '/api/webhooks/email'
      fullPath: '/api/webhooks/email'
      preLoaderRoute: typeof ApiWebhooksEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/facebook': {
      id: '/api/webhooks/facebook'
      path: '/api/webhooks/facebook'
      fullPath: '/api/webhooks/facebook'
      preLoaderRoute: typeof ApiWebhooksFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/indiamart': {
      id: '/api/webhooks/indiamart'
      path: '/api/webhooks/indiamart'
      fullPath: '/api/webhooks/indiamart'
      preLoaderRoute: typeof ApiWebhooksIndiamartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/instagram': {
      id: '/api/webhooks/instagram'
      path: '/api/webhooks/instagram'
      fullPath: '/api/webhooks/instagram'
      preLoaderRoute: typeof ApiWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/gmail/callback': {
      id: '/api/oauth/gmail/callback'
      path: '/api/oauth/gmail/callback'
      fullPath: '/api/oauth/gmail/callback'
      preLoaderRoute: typeof ApiOauthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AiChatRoute: AiChatRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomationRoute: AutomationRoute,
  BroadcastingRoute: BroadcastingRoute,
  ChannelsRoute: ChannelsRoute,
  CommandCenterRoute: CommandCenterRoute,
  CustomersRoute: CustomersRoute,
  EmbedRoute: EmbedRoute,
  HumanSupportRoute: HumanSupportRoute,
  InboxRoute: InboxRoute,
  KnowledgeRoute: KnowledgeRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  CSkuRoute: CSkuRoute,
  DDocumentIdRoute: DDocumentIdRoute,
  ApiCronAutomationsRoute: ApiCronAutomationsRoute,
  ApiWebhooksEmailRoute: ApiWebhooksEmailRoute,
  ApiWebhooksFacebookRoute: ApiWebhooksFacebookRoute,
  ApiWebhooksIndiamartRoute: ApiWebhooksIndiamartRoute,
  ApiWebhooksInstagramRoute: ApiWebhooksInstagramRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
  ApiOauthGmailCallbackRoute: ApiOauthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
